### ISSUE TITLE
Constrained Generator\seq() keeps generating []

### ISSUE THREAD

**Issue by Vinai** [giorgiosironi/eris#100]
Objective: generate a non-empty array of integers.

Code:
```
$this->forAll(
    Generator\suchThat(
        function (array $ints) {
            return count($ints) > 0;
        },
        Generator\seq(Generator\int())
    )
)->then(function (array $ints) {
    // assert something
});
```

Result:
```
Tried to satisfy predicate 100 times, but could not generate a good value. You should try to improve your generator to make it more likely to output good values, or to use a less restrictive condition.
```

Issue: the Generator never produces values.

Raising the number of tries to 1000 doesn't change the outcome.

The same happens with `Generator\filter()` instead of `Generator\suchThat()`.
Maybe I'm not understanding how to use `suchThat`, but I think the above example should be correct.

**Comment by giorgiosironi** [comment]
Can reproduce this. `suchThat()` works by repeatingly trying to extract a value from the inner Generator, and if that value does not satisfy the condition trying again. However, there is a `size` parameter to Generators, which is initially 0 and increases with iterations; the reason is to start with small values like `[]` and the increasing to `[1]`, `[1, 3]` when smaller values do not fail the test. In this case, the first value is `[]` and continues to be as long as `suchThat()` retries, until it reaches its limit.

That's the explanation, I will extend `ForAll` to make it more robust. A workaround in the mean time is to use `when()` which is more integrated with `ForAll`:
```
    public function testSuchThatForANonEmptySequence()
    {   
        $this
            ->forAll(
                Generator\seq(Generator\int())
            )   
            ->when(function (array $ints) {
                return count($ints) > 0;
            })  
            ->then(function (array $ints) {
                $this->assertNotEmpty($ints);
            });                                                                                                                                                           
    }
```
although it can only work on the final generated value and cannot be composed in other Generators.

**Comment by Vinai** [comment]
Thanks for the response and the workaround! Great job!
